{
  "comments": [
    {
      "key": {
        "uuid": "1a494da4_c20f72e0",
        "filename": "sdnvpn/test/functest/run_tempest.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 7165
      },
      "writtenOn": "2018-05-29T07:54:43Z",
      "side": 1,
      "message": "Previously this was the (identical) .conf file under rally. I wonder, what might be the difference/impact?",
      "range": {
        "startLine": 59,
        "startChar": 30,
        "endLine": 59,
        "endChar": 55
      },
      "revId": "1fc59dc868766cc845ecf2a2b7f1fef853d2d7e5",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a494da4_82b60adb",
        "filename": "sdnvpn/test/functest/run_tempest.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 585
      },
      "writtenOn": "2018-05-29T09:26:15Z",
      "side": 1,
      "message": "when Peri was looking into this some time ago, Tempest was only only picking up the conf file in /etc/tempest for some reason we didn\u0027t understand. Hence, Peri added code to copy the Tempest conf file to /etc/tempest (see the comment a few lines above).",
      "parentUuid": "1a494da4_c20f72e0",
      "range": {
        "startLine": 59,
        "startChar": 30,
        "endLine": 59,
        "endChar": 55
      },
      "revId": "1fc59dc868766cc845ecf2a2b7f1fef853d2d7e5",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a494da4_b626e7b8",
        "filename": "sdnvpn/test/functest/run_tempest.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 6895
      },
      "writtenOn": "2018-05-29T13:45:01Z",
      "side": 1,
      "message": "Nikos, Can you just ensure this change makes to execute all the tests in tempest api ? We can troubleshoot the failed testcase separately.",
      "parentUuid": "1a494da4_82b60adb",
      "range": {
        "startLine": 59,
        "startChar": 30,
        "endLine": 59,
        "endChar": 55
      },
      "revId": "1fc59dc868766cc845ecf2a2b7f1fef853d2d7e5",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a494da4_761a9f18",
        "filename": "sdnvpn/test/functest/run_tempest.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 7165
      },
      "writtenOn": "2018-05-29T16:39:51Z",
      "side": 1,
      "message": "(overcloud) bash-4.4# cat tempest-patch-all-1.log | grep FAILED | grep api\n{0} networking_bgpvpn_tempest.tests.api.test_bgpvpn.BgpvpnTest.test_update_route_target [0.447191s] ... FAILED",
      "parentUuid": "1a494da4_b626e7b8",
      "range": {
        "startLine": 59,
        "startChar": 30,
        "endLine": 59,
        "endChar": 55
      },
      "revId": "1fc59dc868766cc845ecf2a2b7f1fef853d2d7e5",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a494da4_16f51b83",
        "filename": "sdnvpn/test/functest/run_tempest.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 585
      },
      "writtenOn": "2018-05-29T20:48:04Z",
      "side": 1,
      "message": "yes, that\u0027s the one I have seen failing for some time.",
      "parentUuid": "1a494da4_761a9f18",
      "range": {
        "startLine": 59,
        "startChar": 30,
        "endLine": 59,
        "endChar": 55
      },
      "revId": "1fc59dc868766cc845ecf2a2b7f1fef853d2d7e5",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a494da4_360c9742",
        "filename": "sdnvpn/test/functest/run_tempest.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 6895
      },
      "writtenOn": "2018-05-30T07:30:06Z",
      "side": 1,
      "message": "we can address this issue separately (may be we should run networking-bgpvpn tempest independently to see issue is with testcase itself)",
      "parentUuid": "1a494da4_16f51b83",
      "range": {
        "startLine": 59,
        "startChar": 30,
        "endLine": 59,
        "endChar": 55
      },
      "revId": "1fc59dc868766cc845ecf2a2b7f1fef853d2d7e5",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}